# Generated by Django 2.2 on 2021-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210304_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '一级菜单'), (2, '二级菜单')], default=1, verbose_name='等级'),
        ),
    ]
