# Generated by Django 2.2 on 2021-03-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_system_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='system',
        ),
        migrations.CreateModel(
            name='BaseUserSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_user_system', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_user_system', to='test_app.System')),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='systems',
            field=models.ManyToManyField(through='test_app.BaseUserSystem', to='test_app.System'),
        ),
    ]
